SELECT CURRENT_REGION();  -- e.g., AWS_AP_SOUTHEAST_1 for India

ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';  -- 'AWS_US,AWS_EU,AZURE_US' etc

ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'AWS_US';
